framework:
  cache:
    default_redis_provider: '%env(string:REDIS_URL)%/0'
    pools:
      cache.http:
        adapter: cache.adapter.redis_tag_aware
        tags: cache.tags
  session:
    handler_id: '%env(string:REDIS_URL)%/1'
  secrets:
    enabled: false
  mailer:
    message_bus: 'messenger.default_bus'

shopware:
  api:
    jwt_key:
      use_app_secret: true
  redis:
    connections:
      persistent:
        dsn: '%env(string:REDIS_URL)%/2?persistent=1'
  number_range:
    increment_storage: 'redis'
    config:
      connection: 'persistent'
  cart:
    storage:
      type: 'redis'
      config:
        connection: 'persistent'
    compress: true
    compression_method: zstd
  cache:
    cache_compression: true
    cache_compression_method: 'zstd'
    tagging:
      each_config: false
      each_snippet: false
      each_theme_config: false
  admin_worker:
    enable_admin_worker: false

monolog:
  handlers:
    main:
      level: error
      buffer_size: 30
    business_event_handler_buffer:
      level: error