services:

  setup-bind-mounts-a-folders:
    image: alpine:3.18
    volumes:
      - type: bind
        source: .tmp/
        target: /appdata/
    env_file: example.env
    command: >
      sh -c "mkdir -p /appdata/data/freshware \
                       /appdata/data/custom \
                       /appdata/data/worker_custom \
                       /appdata/data/tasker_custom \
                       /appdata/data/config/jwt \
                       /appdata/data/files \
                       /appdata/data/var/log \
                       /appdata/data/public/theme \
                       /appdata/data/public/media \
                       /appdata/data/public/bundles \
                       /appdata/data/public/sitemap \
                       /appdata/data/public/thumbnail \
                       /appdata/data/public/js \
                       /appdata/data/public/css && \
             echo 'Successfully created directories under .tmp/'" # Added an echo for confirmation

  php-init:
    image: alpine:3.18
    env_file: example.env
    volumes:
      - type: bind
        source: .tmp/data/freshware
        target: /freshware
      - type: bind
        source: .tmp/data/custom
        target: /var/www/freshware/custom
      - type: bind
        source: .tmp/data/worker_custom
        target: /var/www/freshware/worker_custom
      - type: bind
        source: .tmp/data/tasker_custom
        target: /var/www/freshware/tasker_custom
      - type: bind
        source: .tmp/data/config/jwt
        target: /var/www/freshware/config/jwt
      - type: bind
        source: .tmp/data/files
        target: /var/www/freshware/files
      - type: bind
        source: .tmp/data/var/log
        target: /var/www/freshware/var/log
        #- type: bind
        #source: .tmp/data/var/cache/opcache-preload.php
        #target: /var/www/freshware/var/cache/opcache-preload.php
      - type: bind
        source: .tmp/data/public/theme
        target: /var/www/freshware/public/theme
      - type: bind
        source: .tmp/data/public/media
        target: /var/www/freshware/public/media
      - type: bind
        source: .tmp/data/public/bundles
        target: /var/www/freshware/public/bundles
      - type: bind
        source: .tmp/data/public/sitemap
        target: /var/www/freshware/public/sitemap
      - type: bind
        source: .tmp/data/public/thumbnail
        target: /var/www/freshware/public/thumbnail
      - type: bind
        source: .tmp/data/public/js
        target: /var/www/freshware/public/js
      - type: bind
        source: .tmp/data/public/css
        target: /var/www/freshware/public/css
    depends_on:
      setup-bind-mounts-a-folders:
        condition: service_started
    command: >
      sh -c "chown -vR 33:33 /var/www/freshware/var /var/www/freshware /freshware"
  
  php:
    image: ghcr.io/weselben/freshware:6.6.10.3-v0.2.9
    restart: unless-stopped
    env_file: example.env
    volumes:
      - type: bind
        source: .tmp/data/freshware
        target: /freshware
      - type: bind
        source: .tmp/data/custom
        target: /var/www/freshware/custom
      - type: bind
        source: .tmp/data/config/jwt
        target: /var/www/freshware/config/jwt
      - type: bind
        source: .tmp/data/files
        target: /var/www/freshware/files
      - type: bind
        source: .tmp/data/var/log
        target: /var/www/freshware/var/log
        #- type: bind
        #source: .tmp/data/var/cache/opcache-preload.php
        #target: /var/www/freshware/var/cache/opcache-preload.php
      - type: bind
        source: .tmp/data/public/theme
        target: /var/www/freshware/public/theme
      - type: bind
        source: .tmp/data/public/media
        target: /var/www/freshware/public/media
      - type: bind
        source: .tmp/data/public/bundles
        target: /var/www/freshware/public/bundles
      - type: bind
        source: .tmp/data/public/sitemap
        target: /var/www/freshware/public/sitemap
      - type: bind
        source: .tmp/data/public/thumbnail
        target: /var/www/freshware/public/thumbnail
      - type: bind
        source: .tmp/data/public/js
        target: /var/www/freshware/public/js
      - type: bind
        source: .tmp/data/public/css
        target: /var/www/freshware/public/css
      - example.env:/var/www/freshware/.env:ro
    depends_on:
      php-init:
        condition: service_started
      mariadb:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - freshware_network

  worker:
    image: ghcr.io/weselben/freshware:6.6.10.3-v0.2.9
    restart: unless-stopped
    env_file: example.env
    environment:
      # WORKER_STARTUP=1 is needed to start the tasker instead of the php-fpm process
      - WORKER_STARTUP=1
    volumes:
      - type: bind
        source: .tmp/data/freshware
        target: /freshware
      - type: bind
        source: .tmp/data/worker_custom
        target: /var/www/freshware/worker_custom
      - type: bind
        source: .tmp/data/config/jwt
        target: /var/www/freshware/config/jwt
      - type: bind
        source: .tmp/data/files
        target: /var/www/freshware/files
      - type: bind
        source: .tmp/data/var/log
        target: /var/www/freshware/var/log
      - type: bind
        source: .tmp/data/public/theme
        target: /var/www/freshware/public/theme
      - type: bind
        source: .tmp/data/public/media
        target: /var/www/freshware/public/media
      - type: bind
        source: .tmp/data/public/bundles
        target: /var/www/freshware/public/bundles
      - type: bind
        source: .tmp/data/public/sitemap
        target: /var/www/freshware/public/sitemap
      - type: bind
        source: .tmp/data/public/thumbnail
        target: /var/www/freshware/public/thumbnail
      - type: bind
        source: .tmp/data/public/js
        target: /var/www/freshware/public/js
      - type: bind
        source: .tmp/data/public/css
        target: /var/www/freshware/public/css
      - example.env:/var/www/freshware/.env:ro
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      php:
        condition: service_started
    networks:
      - freshware_network

  tasker:
    image: ghcr.io/weselben/freshware:6.6.10.3-v0.2.9
    restart: unless-stopped
    env_file: example.env
    environment:
      # TASKER_STARTUP=1 is needed to start the tasker instead of the php-fpm process
      - TASKER_STARTUP=1
    volumes:
      - type: bind
        source: .tmp/data/freshware
        target: /freshware
      - type: bind
        source: .tmp/data/tasker_custom
        target: /var/www/freshware/tasker_custom
      - type: bind
        source: .tmp/data/config/jwt
        target: /var/www/freshware/config/jwt
      - type: bind
        source: .tmp/data/files
        target: /var/www/freshware/files
      - type: bind
        source: .tmp/data/var/log
        target: /var/www/freshware/var/log
        #- type: bind
        #source: .tmp/data/var/cache/opcache-preload.php
        #target: /var/www/freshware/var/cache/opcache-preload.php
      - type: bind
        source: .tmp/data/public/theme
        target: /var/www/freshware/public/theme
      - type: bind
        source: .tmp/data/public/media
        target: /var/www/freshware/public/media
      - type: bind
        source: .tmp/data/public/bundles
        target: /var/www/freshware/public/bundles
      - type: bind
        source: .tmp/data/public/sitemap
        target: /var/www/freshware/public/sitemap
      - type: bind
        source: .tmp/data/public/thumbnail
        target: /var/www/freshware/public/thumbnail
      - type: bind
        source: .tmp/data/public/js
        target: /var/www/freshware/public/js
      - type: bind
        source: .tmp/data/public/css
        target: /var/www/freshware/public/css
      - example.env:/var/www/freshware/.env:ro
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      php:
        condition: service_started
    networks:
      - freshware_network

  mariadb:
    image: mariadb:11.6.2
    env_file: example.env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - freshware_network

  redis:
    image: redis:6.2
    env_file: example.env
    volumes:
      - redis_data:/data
    networks:
      - freshware_network

  rabbitmq:
    image: rabbitmq:4.0.8-management
    restart: unless-stopped
    env_file: example.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - freshware_network

  nginx:
    image: nginx:latest
    env_file: example.env
    volumes:
      - /freshware/nginx.conf:/etc/nginx/nginx.conf
      - /freshware/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - type: bind
        source: .tmp/data/files
        target: /var/www/freshware/files
        read_only: true
      - type: bind
        source: .tmp/data/public/theme
        target: /var/www/freshware/public/theme
        read_only: true
      - type: bind
        source: .tmp/data/public/media
        target: /var/www/freshware/public/media
        read_only: true
      - type: bind
        source: .tmp/data/public/bundles
        target: /var/www/freshware/public/bundles
        read_only: true
      - type: bind
        source: .tmp/data/public/sitemap
        target: /var/www/freshware/public/sitemap
        read_only: true
      - type: bind
        source: .tmp/data/public/thumbnail
        target: /var/www/freshware/public/thumbnail
        read_only: true
      - type: bind
        source: .tmp/data/public/js
        target: /var/www/freshware/public/js
        read_only: true
      - type: bind
        source: .tmp/data/public/css
        target: /var/www/freshware/public/css
        read_only: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      php:
        condition: service_started
    networks:
      - freshware_network

volumes:
  mariadb_data:
  rabbitmq_data:
  redis_data:

networks:
  freshware_network: